---
- name: 'cumulus management and oob switch configuration builder'
  hosts: mgmt
  gather_facts: false

  vars:
    node_expected_keys:
      [
        'hostname',
        'device_type',
        'lo_ip',
      ]

  tasks:
    - name: Set Timestamp
      set_fact: time_stamp="{{ lookup('pipe','date \"+%m-%d-%Y_%H%M\"') }}"
      tags:
        - pre_config

    - name: Obtain {{ inventory_hostname }}.yml
      include_vars: ../hostvars/cumulus/mgmt/{{ inventory_hostname }}.yml
      when: (inventory_hostname in groups ['mgmt'])
      tags:
        - pre_config

    - name: Build Configuration from Template
      ansible.builtin.template:
        src: templates/mgmt_build.j2
        dest: outputs/mgmt/{{ inventory_hostname }}_{{ time_stamp }}.sh
      when: (inventory_hostname in groups ['mgmt'])
      tags:
        - pre_config
...